# Generated by Django 2.1.5 on 2019-02-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gpcr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lig_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('gpcr', models.ManyToManyField(through='gpcrdb.Binds', to='gpcrdb.Gpcr')),
            ],
        ),
        migrations.AddField(
            model_name='binds',
            name='gpcr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpcrdb.Gpcr'),
        ),
        migrations.AddField(
            model_name='binds',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpcrdb.Ligand'),
        ),
    ]
