# Generated by Django 2.0.6 on 2019-04-12 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity', models.FloatField(blank=True, null=True)),
                ('affinity_type', models.CharField(choices=[('i', 'Ki'), ('d', 'Kd'), ('m', 'Km'), ('e', 'EC50'), ('z', 'IC50')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gpcr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=4, unique=True)),
                ('gpcr_name', models.CharField(max_length=250)),
                ('gpcr_class', models.CharField(choices=[('a', 'Class A'), ('b', 'Class B (Secretin)'), ('c', 'Class C (Glutamate)'), ('d', 'Adhesion'), ('f', 'Frizzled')], max_length=1, null=True)),
                ('family', models.CharField(max_length=250)),
                ('subfamily', models.CharField(max_length=250)),
                ('uniprot_id', models.CharField(max_length=250)),
                ('species', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('method', models.CharField(choices=[('a', 'Class A'), ('b', 'Class B (Secretin)'), ('c', 'Class C (Glutamate)'), ('d', 'Adhesion'), ('f', 'Frizzled')], max_length=1, null=True)),
                ('resolution', models.FloatField(null=True)),
                ('pubmed_id', models.IntegerField(null=True)),
                ('deposition_date', models.DateField(null=True)),
                ('modification_date', models.DateField(null=True)),
                ('raw_pdb_file', models.FileField(null=True, upload_to='raw_pdbs/')),
                ('mapping_pdb_file', models.FileField(null=True, upload_to='mapped_pdb/')),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lig_id', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('smiles', models.CharField(max_length=250)),
                ('mol_weight', models.FloatField()),
                ('gpcr', models.ManyToManyField(through='gpcrdb.Binds', to='gpcrdb.Gpcr')),
            ],
        ),
        migrations.CreateModel(
            name='Similarities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmsd', models.FloatField()),
                ('sequence', models.FloatField()),
                ('gpcr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpcr1', to='gpcrdb.Gpcr')),
                ('gpcr2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpcr2', to='gpcrdb.Gpcr')),
            ],
        ),
        migrations.AddField(
            model_name='gpcr',
            name='rmsd_values',
            field=models.ManyToManyField(through='gpcrdb.Similarities', to='gpcrdb.Gpcr'),
        ),
        migrations.AddField(
            model_name='binds',
            name='gpcr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpcrdb.Gpcr'),
        ),
        migrations.AddField(
            model_name='binds',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gpcrdb.Ligand'),
        ),
    ]
