# Generated by Django 2.0.6 on 2019-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpcr',
            name='gene_name',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
