# Generated by Django 2.0.6 on 2019-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpcr',
            name='family',
        ),
        migrations.AlterField(
            model_name='gpcr',
            name='method',
            field=models.CharField(choices=[('x', 'X-Ray Diffraction'), ('n', 'Solution NMR')], default='x', max_length=1),
            preserve_default=False,
        ),
    ]
