# Generated by Django 2.0.6 on 2019-03-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0002_auto_20190220_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpcr',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='gpcr',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='gpcr',
            name='exp_method',
        ),
        migrations.RemoveField(
            model_name='gpcr',
            name='organism',
        ),
        migrations.RemoveField(
            model_name='gpcr',
            name='title',
        ),
        migrations.AddField(
            model_name='binds',
            name='affinity_type',
            field=models.CharField(choices=[('i', 'Ki'), ('d', 'Kd'), ('m', 'Km'), ('e', 'EC50'), ('z', 'IC50')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='mol_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligand',
            name='smiles',
            field=models.CharField(default=23, max_length=250),
            preserve_default=False,
        ),
    ]
