# Generated by Django 2.0.6 on 2019-04-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0002_auto_20190412_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpcr',
            name='modification_date',
        ),
        migrations.AddField(
            model_name='gpcr',
            name='reference',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gpcr',
            name='method',
            field=models.CharField(choices=[('x', 'X-Ray Diffraction'), ('n', 'Solution NMR'), ('s', 'Solid-State NMR'), ('e', 'Electron Microscopy')], max_length=1),
        ),
        migrations.AlterField(
            model_name='gpcr',
            name='resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpcr',
            name='subfamily',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
