# Generated by Django 2.0.6 on 2019-03-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0003_auto_20190329_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similarities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmsd', models.FloatField()),
                ('sequence', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='gpcr',
            name='rmsd_values',
            field=models.ManyToManyField(through='gpcrdb.Similarities', to='gpcrdb.Gpcr'),
        ),
    ]
