# Generated by Django 2.0.6 on 2019-04-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0003_auto_20190414_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligand',
            old_name='smiles',
            new_name='inchi_key',
        ),
        migrations.RenameField(
            model_name='ligand',
            old_name='name',
            new_name='lig_name',
        ),
        migrations.RemoveField(
            model_name='ligand',
            name='mol_weight',
        ),
    ]
