# Generated by Django 2.0.6 on 2019-04-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0004_auto_20190415_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binds',
            name='affinity',
        ),
        migrations.RemoveField(
            model_name='binds',
            name='affinity_type',
        ),
        migrations.AddField(
            model_name='gpcr',
            name='fasta',
            field=models.FileField(max_length=1000, null=True, upload_to=''),
        ),
    ]
