# Generated by Django 2.0.6 on 2019-03-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0004_auto_20190330_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarities',
            name='gpcr1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='gpcrdb.Gpcr'),
            preserve_default=False,
        ),
    ]
