# Generated by Django 2.1.5 on 2019-04-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0005_auto_20190425_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gene_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='gpcr',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene', to='gpcrdb.Gene'),
        ),
    ]
