# Generated by Django 2.0.6 on 2019-03-30 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0005_similarities_gpcr1'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarities',
            name='gpcr2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gpcr2', to='gpcrdb.Gpcr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='similarities',
            name='gpcr1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpcr1', to='gpcrdb.Gpcr'),
        ),
    ]
