# Generated by Django 2.0.6 on 2019-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0005_auto_20190416_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpcr',
            name='fasta',
            field=models.FileField(null=True, upload_to='fastas/'),
        ),
    ]
