# Generated by Django 2.1.5 on 2019-04-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0006_auto_20190426_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpcr',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpcrdb.Gene'),
        ),
    ]
