# Generated by Django 2.0.6 on 2019-03-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpcrdb', '0006_auto_20190330_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpcr',
            name='pdb_file',
            field=models.FileField(null=True, upload_to='pdbs/'),
        ),
    ]
